name: Main

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Build, Format
    runs-on: ubuntu-latest
    steps:
      - uses: titanom/github-composite-actions/turbo/setup@v1.0.12
        with:
          pnpm-version: 8

      - name: Check Format
        run: pnpm format:check

      - name: Build
        run: pnpm build
